// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import Config from "react-native-ultimate-config";
const awsExports = JSON.parse(Config.AWS_EXPORTS);

export default awsExports;
