require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'marlowCrewCompanion' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'marlowCrewCompanionTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
        if config.name == 'Staging'
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
        end
    end
    # installer.pods_project.build_configurations.each do |config|
    #   if config.name == 'Staging'
    #     config.build_settings['CONFIGURATION_TEMP_DIR'] = '$(PROJECT_TEMP_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
    #     config.build_settings['CONFIGURATION_BUILD_DIR'] = '$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
    #   end
    # end
    # installer.pods_project.targets.each do |target|
    #   target.build_configurations.each do |config|
    #     if config.name == 'Staging'
    #       config.build_settings['CONFIGURATION_TEMP_DIR'] = '$(PROJECT_TEMP_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
    #       config.build_settings['PODS_CONFIGURATION_BUILD_DIR'] = '${PODS_BUILD_DIR}/Release$(EFFECTIVE_PLATFORM_NAME)'
    #     end
    #   end
    # end
  end
end

target 'marlowCrewCompanion-tvOS' do
  # Pods for marlowCrewCompanion-tvOS

  target 'marlowCrewCompanion-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
