export const GET_ASSIGNMENT_DETAILS = "GET_ASSIGNMENT_DETAILS";
export const GET_ASSIGNMENT_DETAILS_SUCCESS = "GET_ASSIGNMENT_DETAILS_SUCCESS";
export const GET_ASSIGNMENT_DETAILS_FAIL = "GET_ASSIGNMENT_DETAILS_FAIL";
export const SET_REFRESHING_ASSIGNMENT_DETAILS =
  "SET_REFRESHING_ASSIGNMENT_DETAILS";
