export const GET_CONTACT_DETAILS = "GET_CONTACT_DETAILS";
export const SET_REFRESHING_CONTACT_DETAILS = "SET_REFRESHING_CONTACT_DETAILS";
export const GET_CONTACT_DETAILS_SUCCESS = "GET_CONTACT_DETAILS_SUCCESS";
export const GET_CONTACT_DETAILS_FAIL = "GET_CONTACT_DETAILS_FAIL";
