export const GET_COVID_DOCUMENT = "GET_COVID_DOCUMENT";
export const SET_IS_LOADING_COVID = "SET_IS_LOADING_COVID";
export const GET_COVID_DOCUMENT_SUCCESS = "GET_COVID_DOCUMENT_SUCCESS";
export const GET_COVID_DOCUMENT_FAIL = "GET_COVID_DOCUMENT_FAIL";
