export const GET_FLIGHTS_DETAILS = "GET_FLIGHTS_DETAILS";
export const GET_FLIGHTS_DETAILS_SUCCESS = "GET_FLIGHTS_DETAILS_SUCCESS";
export const GET_FLIGHTS_DETAILS_FAIL = "GET_FLIGHTS_DETAILS_FAIL";
export const SET_REFRESHING_FLIGHT_DETAILS = "SET_REFRESHING_FLIGHT_DETAILS";
