export const GET_IMPRINT_DETAILS = "GET_IMPRINT_DETAILS";
export const GET_IMPRINT_DETAILS_SUCCESS = "GET_IMPRINT_DETAILS_SUCCESS";
export const GET_IMPRINT_DETAILS_FAIL = "GET_IMPRINT_DETAILS_FAIL";
