export const GET_ALL_NEWS = "GET_ALL_NEWS";
export const GET_ALL_NEWS_SUCCESS = "GET_ALL_NEWS_SUCCESS";
export const GET_ALL_NEWS_FAIL = "GET_ALL_NEWS_FAIL";
export const SET_REFRESHING_NEWS = "SET_REFRESHING_NEWS";
