export const GET_NOTIFICATIONS_DETAILS = "GET_NOTIFICATIONS_DETAILS";
export const GET_NOTIFICATIONS_DETAILS_SUCCESS =
  "GET_NOTIFICATIONS_DETAILS_SUCCESS";
export const GET_NOTIFICATIONS_DETAILS_FAIL = "GET_NOTIFICATIONS_DETAILS_FAIL";
export const SEND_NOTIFICATIONS_DETAILS = "SEND_NOTIFICATIONS_DETAILS";
export const SEND_NOTIFICATIONS_DETAILS_SUCCESS =
  "SEND_NOTIFICATIONS_DETAILS_SUCCESS";
export const SEND_NOTIFICATIONS_DETAILS_FAIL =
  "SEND_NOTIFICATIONS_DETAILS_FAIL";
export const SET_RING_BELL = "SET_RING_BELL";
export const SET_RING_BELL_SUCCESS = "SET_RING_BELL_SUCCESS";
export const SET_RING_BELL_FAIL = "SET_RING_BELL_FAIL";
export const SET_REFRESHING_NOTIFICATIONS_DETAILS =
  "SET_REFRESHING_NOTIFICATIONS_DETAILS";
