export const GET_PRIVACY_POLICY_DETAILS = "GET_PRIVACY_POLICY_DETAILS";
export const GET_PRIVACY_POLICY_DETAILS_SUCCESS =
  "GET_PRIVACY_POLICY_DETAILS_SUCCESS";
export const GET_PRIVACY_POLICY_DETAILS_FAIL =
  "GET_PRIVACY_POLICY_DETAILS_FAIL";
