//Payslips & Allotments Details
export const GET_PAYSLIP_DETAILS = "GET_PAYSLIP_DETAILS";
export const SET_REFRESHING_PAYSLIP_DETAILS = "SET_REFRESHING_PAYSLIP_DETAILS";
export const GET_PAYSLIP_DETAILS_SUCCESS = "GET_PAYSLIP_DETAILS_SUCCESS";
export const GET_PAYSLIP_DETAILS_FAIL = "GET_PAYSLIP_DETAILS_FAIL";
export const SET_IS_DOWNLOADING_PAYSLIP_SUCCESS =
  "SET_IS_DOWNLOADING_PAYSLIP_SUCCESS";
//PDF Section
export const GET_PAYSLIP_DOCUMENTS_FILE = "GET_PAYSLIP_DOCUMENTS_FILE";
export const GET_PAYSLIP_DOCUMENTS_FILE_SUCCESS =
  "GET_PAYSLIP_DOCUMENTS_FILE_SUCCESS";
export const GET_PAYSLIP_DOCUMENTS_FILE_FAIL =
  "GET_PAYSLIP_DOCUMENTS_FILE_FAIL";
export const REMOVE_PAYSLIP_DOCUMENTS_FILE = "REMOVE_PAYSLIP_DOCUMENTS_FILE";
export const REMOVE_PAYSLIP_DOCUMENTS_FILE_SUCCESS =
  "REMOVE_PAYSLIP_DOCUMENTS_FILE_SUCCESS";
export const REMOVE_PAYSLIP_DOCUMENTS_FILE_FAILED =
  "REMOVE_PAYSLIP_DOCUMENTS_FILE_FAILED";
export const SET_LOADING_NEW_PAYSLIP = "SET_LOADING_NEW_PAYSLIP";
