export const GET_ALL_SEAFARER_DETAILS = "GET_ALL_SEAFARER_DETAILS";
export const GET_ALL_SEAFARER_DETAILS_SUCCESS =
  "GET_ALL_SEAFARER_DETAILS_SUCCESS";
export const GET_ALL_SEAFARER_DETAILS_FAIL = "GET_ALL_SEAFARER_DETAILS_FAIL";
export const SET_REFRESHING_SEAFARER_DETAILS =
  "SET_REFRESHING_SEAFARER_DETAILS";
export const SET_IS_LOADING_DATA = "SET_IS_LOADING_DATA";
