export const GET_SEAFARER_DOCUMENTS = "GET_SEAFARER_DOCUMENTS";
export const SET_REFRESHING_SEAFARER_DOCUMENTS =
  "SET_REFRESHING_SEAFARER_DOCUMENTS";
export const GET_SEAFARER_DOCUMENTS_SUCCESS = "GET_SEAFARER_DOCUMENTS_SUCCESS";
export const GET_SEAFARER_DOCUMENTS_FAIL = "GET_SEAFARER_DOCUMENTS_FAIL";
export const GET_SEAFARER_DOCUMENTS_FILE = "GET_SEAFARER_DOCUMENTS_FILE";
export const SET_LOADING_NEW_DOCUMENT = "SET_LOADING_NEW_DOCUMENT";
export const SET_IS_DOWNLOADING_DOCUMENT_SUCCESS =
  "SET_IS_DOWNLOADING_DOCUMENT_SUCCESS";

export const GET_SEAFARER_DOCUMENTS_FILE_SUCCESS =
  "GET_SEAFARER_DOCUMENTS_FILE_SUCCESS";
export const GET_SEAFARER_DOCUMENTS_FILE_FAIL =
  "GET_SEAFARER_DOCUMENTS_FILE_FAIL";
export const REMOVE_SEAFARER_DOCUMENT = "REMOVE_SEAFARER_DOCUMENT";
export const REMOVE_SEAFARER_DOCUMENT_SUCCESS =
  "REMOVE_SEAFARER_DOCUMENT_SUCCESS";
export const REMOVE_SEAFARER_DOCUMENT_FAILED =
  "REMOVE_SEAFARER_DOCUMENT_FAILED";
