export const GET_SEA_SERVICE_DETAILS = "GET_SEA_SERVICE_DETAILS";
export const SET_REFRESHING_SEA_SERVICE_DETAILS =
  "SET_REFRESHING_SEA_SERVICE_DETAILS";
export const GET_SEA_SERVICE_DETAILS_SUCCESS =
  "GET_SEA_SERVICES_DETAILS_SUCCESS";
export const GET_SEA_SERVICE_DETAILS_FAIL = "GET_SEA_SERVICES_DETAILS_FAIL";
