export const GET_TERMS_AND_CONDITIONS_DETAILS =
  "GET_TERMS_AND_CONDITIONS_DETAILS";
export const GET_TERMS_AND_CONDITIONS_DETAILS_SUCCESS =
  "GET_TERMS_AND_CONDITIONS_DETAILS_SUCCESS";
export const GET_TERMS_AND_CONDITIONS_DETAILS_FAIL =
  "GET_TERMS_AND_CONDITIONS_DETAILS_FAIL";
