export const GET_WORKING_CLOTHES_DETAILS = "GET_WORKING_CLOTHES_DETAILS";
export const GET_WORKING_CLOTHES_DETAILS_SUCCESS =
  "GET_WORKING_CLOTHES_DETAILS_SUCCESS";
export const GET_WORKING_CLOTHES_DETAILS_FAIL =
  "GET_WORKING_CLOTHES_DETAILS_FAIL";
export const SET_REFRESHING_WORKING_CLOTHES_DETAILS =
  "SET_REFRESHING_WORKING_CLOTHES_DETAILS";
